### ISSUE TITLE
$$Text.Format call in extendedProperties results in a value of 'System.Object'

### ISSUE THREAD

**Issue by RobinHSanner** [gbrueckl/Azure.DataFactory.CustomActivityDebugger#7]
Using the $$Text.Format functions in extendedProperties results in a value of 'System.Object' when the activity runs.

**Comment by gbrueckl** [comment]
Hi Robin,

please use the updated version at https://github.com/gbrueckl/Azure.DataFactory.LocalEnvironment
the issue should be fixed there.
I assume that this was related to the fact that this version distinguished between upper and lower-case when you wrote "SliceStart" in your JSON definition
this is fixed in the new version

I also updated the README.md accordingly to link to the new Repository

-gerhard
